version: "3.8"

services:
  postgres:
    container_name: superkma-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "45432:5432"
    env_file:
      - ./.env/.postgresql.env
    networks:
      - skma

volumes:
  postgres:

networks:
  skma:
    name: superkma
    external: true