global:
  scrape_interval: 5s

scrape_configs:
  - job_name: host-server
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080