version: "3.8"

services:
  keycloak:
    container_name: superkma-keycloak
    image: quay.io/keycloak/keycloak:23.0
    command: start
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      KC_DB: "postgres"
      KC_DB_URL_HOST: "postgres"
      KC_DB_USERNAME: "keycloak"
      KC_DB_URL_DATABASE: "keycloak"
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    networks:
      - skma
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  skma:
    name: superkma
    external: true