version: "3.8"

services:
  keycloak:
    container_name: superkma-keycloak
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8443:8443
    environment:
      KC_DB: "postgres"
      KC_DB_URL_HOST: "postgres"
      KC_DB_USERNAME: "keycloak"
      KC_DB_URL_DATABASE: "keycloak"
      KC_HTTPS_CERTIFICATE_FILE: "/opt/keycloak/conf/cert/server.crt.pem"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/opt/keycloak/conf/cert/server.key.pem"
    volumes:
      - ../keycloak/cert:/opt/keycloak/conf/cert
    env_file:
      - ../.env
    networks:
      - skma

networks:
  skma:
    name: superkma
    external: true