version: "3.8"

services:
  keycloak:
    extends:
      file: keycloak/compose-base.yaml
      service: keycloak
    environment:
      KC_PROXY: "edge"
      PROXY_ADDRESS_FORWARDING: true
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: "nginx-pm"