version: "3.8"

services:
  keycloak:
    extends:
      file: keycloak/compose-base.yaml
      service: keycloak
    ports:
      - 8443:8443
    environment:
      KC_HTTPS_CERTIFICATE_FILE: "/opt/keycloak/conf/cert/server.crt.pem"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/opt/keycloak/conf/cert/server.key.pem"
    volumes:
      - ../keycloak/cert:/opt/keycloak/conf/cert