version: "3.8"

services:
  keycloak:
    container_name: superkma-keycloak
    image: quay.io/keycloak/keycloak:23.0
    command: start
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      KC_DB: "postgres"
      KC_DB_URL_HOST: "postgres"
      KC_DB_USERNAME: "keycloak"
      KC_DB_URL_DATABASE: "keycloak"
      KC_PROXY: "edge"
      PROXY_ADDRESS_FORWARDING: true
    env_file:
      - ../.env
    networks:
      - skma
      - proxy

networks:
  skma:
    name: superkma
    external: true
  
  proxy:
    external: true
    name: "nginx-pm"