version: "3.8"

services:
  keycloak:
    container_name: superkma_keycloak
    image: bitnami/keycloak:22.0.1
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_PRODUCTION=true
      - KEYCLOAK_PROXY=edge
    env_file:
      - ../.env
    networks:
      - skma

networks:
  skma:
    name: superkma
    external: true