version: '3.8'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - observability

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    command:
      - --docker_only
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ../observability/prometheus:/etc/prometheus
    restart: unless-stopped
    depends_on:
      - node-exporter
      - cadvisor
    ports:
      - 9090:9090
    networks:
      - proxy
      - observability
      - skma

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ../observability/grafana:/etc/grafana/provisioning/
    restart: unless-stopped
    networks:
      - proxy
      - observability
      - skma

volumes:
  prometheus_data:
  grafana_data:

networks:
  proxy:
    external: true
    name: "nginx-pm"

  observability:

  skma:
    name: superkma
    external: true