version: "3.8"

include:
  - path:
    - observability/requires.yaml

services:
  node-exporter:
    extends:
      file: observability/services.yaml
      service: node-exporter

  cadvisor:
    extends:
      file: observability/services.yaml
      service: cadvisor

  prometheus:
    extends:
      file: observability/services.yaml
      service: prometheus

  tempo:
    extends:
      file: observability/services.yaml
      service: tempo

  loki:
    extends:
      file: observability/services.yaml
      service: loki

  promtail:
    extends:
      file: observability/services.yaml
      service: promtail

  otel-collector:
    extends:
      file: observability/services.yaml
      service: otel-collector
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  grafana:
    extends:
      file: observability/services.yaml
      service: grafana
    ports:
      - 3000:3000