version: "3.8"

services:
  mongodb:
    container_name: superkma-mongodb
    image: mongo:7
    restart: unless-stopped
    ports:
      - "47017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env/.mongodb.env
    networks:
      - skma
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:

networks:
  skma:
    name: superkma
    external: true