version: "3.8"

services:
  quantum:
    container_name: kma-quantum
    restart: unless-stopped
    image: ghcr.io/kma-score/quantum:latest
    depends_on:
      - redis
      - mongodb
    env_file:
      - ../.env/.quantum.env
    networks:
      - skma
    environment:
      DATABASE_URI: mongodb://superkma-mongodb:27017
      REDIS_HOST: superkma-redis
      REDIS_PORT: 6379
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:3000 || exit 1z
      interval: 15s
      timeout: 10s
      retries: 5

networks:
  skma:
    name: superkma
    external: true
